nome = input("Insira seu nome ")
idade = int(input("Insira sua idade "))
altura = float(input("Insira sua altura "))
print("Seu nome e ", nome)
print("Voce tem ", idade," anos de idade")
print("Voce mede ", altura, " de altura")
